imie = input('Podaj Imie: ')
uczelnia = input('Uczelnia: ')
kierunek = input("Podaj kierunek: ")
wiek = int(input("Podaj wiek: "))
print("Witaj {a} z uczelni {b} z kierunku {c} \nMasz {w} lat".format(a=imie , b=uczelnia , c=kierunek , w=wiek))